### ISSUE TITLE
How to install a local .egg?

### ISSUE THREAD

**Issue by Massimo-B** [trac-hacks/tracsql#4]
Doing as a user
```
python2.7 setup.py install
```
fails of course with
```
error: could not create '/usr/lib64/python2.7/site-packages/tracsql': Permission denied
```
Doing
```
python2.7 setup.py bdist_egg
```
as I do with almost every other plugin it fails with
```
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
```
Why is the installation so different?
How do I create a local .egg of this plugin?

**Comment by rjollos** [comment]
> Doing as a user
> 
> ```
> python2.7 setup.py install
> ```
> 
> fails of course with
> 
> ```
> error: could not create '/usr/lib64/python2.7/site-packages/tracsql': Permission denied
> ```

You probably need to run as `sudo`

> Doing
> 
> ```
> python2.7 setup.py bdist_egg
> ```
> 
> as I do with almost every other plugin it fails with
> 
> ```
> /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
> ```
> 
> Why is the installation so different?
> How do I create a local .egg of this plugin?

Please try again after a4f0edf.

**Comment by Massimo-B** [comment]
> Please try again after [a4f0edf](https://github.com/trac-hacks/tracsql/commit/a4f0edfc98c22cf31f75aa6add6676d9a47c4ce6).

This works, thanks.

Now I have at least tracsql and WikiTableMacro working for plain SQL commands.
Btw. are all those SQL plugins safe from CREATE, UPDATE and DELETE or do they provide full access to the database? It would be useful for any of those plugins, to grant read-only access only or read-write by configuration option.
On the other hand I could also create a read-only user account for this purpose.

**Comment by rjollos** [comment]
> Btw. are all those SQL plugins safe from CREATE, UPDATE and DELETE or do they provide full access to the database? It would be useful for any of those plugins, to grant read-only access only or read-write by configuration option.

Both plugins use a read-only transaction manager (`db_query` rather than `db_transaction`), so `CREATE`, `UPDATE` and `DELETE` are not allowed.
